/**
 * Predefined suggestions for character identity trait fields.
 * Players can select from these or type their own custom values.
 */

export const CALLING_SUGGESTIONS = [
  'The Adventurer',
  'The Wanderer',
  'The Protector',
  'The Seeker',
  'The Outcast',
  'The Scholar',
  'The Guardian',
  'The Healer',
  'The Hunter',
  'The Performer',
  'The Mystic',
  'The Warrior',
  'The Diplomat',
  'The Merchant',
  'The Trickster',
  'The Leader',
  'The Sage',
  'The Artisan',
  'The Explorer',
  'The Rebel',
  'The Peacemaker',
  'The Avenger',
  'The Redeemed',
  'The Dreamer',
  'The Survivor',
  'The Chosen One',
  'The Lost Soul',
  'The Champion',
  'The Faithful',
  'The Rogue',
] as const;

export const PRONOUNS_SUGGESTIONS = [
  'he/him',
  'she/her',
  'they/them',
  'he/they',
  'she/they',
  'ze/zir',
  'xe/xem',
  'it/its',
  'any pronouns',
] as const;

export const EYE_SUGGESTIONS = [
  'Amber',
  'Blue',
  'Brown',
  'Golden',
  'Gray',
  'Green',
  'Hazel',
  'Heterochromatic',
  'Milky white',
  'Purple',
  'Red',
  'Silver',
  'Black',
  'Glowing',
  'Slitted pupils',
  'Compound',
  'Crystalline',
  'Starlit',
  'Fiery orange',
  'Pale blue',
  'Deep violet',
  'Emerald green',
  'Bright yellow',
  'Opalescent',
  'Pitch black',
  'White with no pupil',
  'One eye missing',
  'Catlike',
] as const;

export const HAIR_SUGGESTIONS = [
  'Bald',
  'Black',
  'Blonde',
  'Brown',
  'Auburn',
  'Red',
  'Gray',
  'White',
  'Silver',
  'Blue',
  'Green',
  'Purple',
  'Pink',
  'Long and flowing',
  'Short and cropped',
  'Braided',
  'Dreadlocks',
  'Curly',
  'Straight',
  'Wavy',
  'Shaved sides',
  'Mohawk',
  'Leaves and vines',
  'Crystalline strands',
  'Streaked with gray',
  'Tied back in a ponytail',
  'Wild and unkempt',
  'Neatly combed',
  'Hidden under a hood',
  'Adorned with beads',
  'Multicolored',
  'Flame-like',
  'Feathered',
] as const;

export const SKIN_SUGGESTIONS = [
  'Pale',
  'Fair',
  'Olive',
  'Tan',
  'Brown',
  'Dark brown',
  'Ebony',
  'Copper',
  'Bronze',
  'Golden',
  'Scaled',
  'Bark-like',
  'Metallic',
  'Stone-textured',
  'Freckled',
  'Tattooed',
  'Scarred',
  'Luminescent',
  'Chitinous',
  'Feathered',
  'Weathered',
  'Smooth',
  'Wrinkled',
  'Patterned with markings',
  'Iridescent',
  'Mottled',
  'Ashen',
  'Ruddy',
  'Sunburnt',
  'Covered in runes',
] as const;

export const BODY_SUGGESTIONS = [
  'Tall and slender',
  'Short and stocky',
  'Muscular',
  'Lithe',
  'Athletic',
  'Heavyset',
  'Petite',
  'Lanky',
  'Broad-shouldered',
  'Average build',
  'Wiry',
  'Compact',
  'Towering',
  'Delicate',
  'Sturdy',
  'Gaunt',
  'Burly',
  'Graceful',
  'Hunched',
  'Imposing',
  'Slight',
  'Rotund',
  'Scarred and battle-worn',
  'Elegant',
  'Rugged',
] as const;

export const CLOTHING_SUGGESTIONS = [
  'Practical traveling clothes',
  'Ornate robes',
  'Leather armor',
  'Simple peasant garb',
  'Noble attire',
  'Flowing cloaks',
  'Dark hooded clothing',
  'Colorful patterns',
  'Military uniform',
  'Religious vestments',
  'Artisan work clothes',
  'Adventuring gear',
  'Worn and patched',
  'Pristine and well-maintained',
  'Nature-inspired attire',
  'Merchant finery',
  'Tribal garments',
  'Scholar robes',
  'Sailor outfit',
  'Performer costume',
  'Hunting leathers',
  'Chain mail',
  'Plate armor',
  'Exotic silks',
  'Fur-lined cloak',
  'Tattered rags',
  'Ceremonial dress',
  'Disguise or mask',
  'Minimalist attire',
  'Layered and practical',
] as const;

export const MANNERISM_SUGGESTIONS = [
  'Speaks softly',
  'Speaks loudly',
  'Formal speech',
  'Casual slang',
  'Nervous ticks',
  'Confident posture',
  'Fidgets constantly',
  'Thoughtful pauses',
  'Quick to laugh',
  'Reserved demeanor',
  'Expressive gestures',
  'Monotone voice',
  'Melodic voice',
  'Gruff tone',
  'Always smiling',
  'Rarely makes eye contact',
  'Intense stare',
  'Hums when thinking',
  'Taps fingers',
  'Paces when anxious',
  'Cracks knuckles',
  'Strokes chin thoughtfully',
  'Raises one eyebrow',
  'Laughs nervously',
  'Speaks in riddles',
  'Uses elaborate hand gestures',
  'Whispers secrets',
  'Always alert and watching',
  'Tends to interrupt',
  'Speaks with an accent',
  'Quotes proverbs often',
  'Sighs dramatically',
] as const;

export const EXPERIENCE_SUGGESTIONS = [
  'Acrobatics',
  'Administration',
  'Alchemy',
  'Ambusher',
  'Ancient Knowledge',
  'Animal Handling',
  'Arcana',
  'Aristocrat',
  'Athletics',
  'Blacksmith',
  'Blend In',
  'Bloodhound',
  'Bloodthirsty',
  'Boundless Knowledge',
  'Camouflage',
  'Coercion',
  'Collateral Damage',
  'Command',
  'Commander',
  'Conquest',
  'Cooking',
  'Copycat',
  'Courtier',
  'Criminal Underworld',
  'Deception',
  'Diplomacy',
  'Disguise',
  'Divine Knowledge',
  'Engineering',
  'Espionage',
  'Fallen Lore',
  'Forbidden Knowledge',
  'Forest Knowledge',
  'Herbalism',
  'High Society',
  'History',
  'Huge',
  'Hunt from Above',
  'Hunting',
  'Infiltration',
  'Intimidation',
  'Intrusion',
  'Investigation',
  'Keen Senses',
  'Leadership',
  'Local Knowledge',
  'Lockpicking',
  'Magical Knowledge',
  'Manipulation',
  'Medicine',
  'Merchant',
  'Music',
  'Nature',
  'Navigation',
  'Negotiation',
  'Nobility',
  'Noble Etiquette',
  'Nocturnal Hunter',
  'Performance',
  'Persuasion',
  'Protect What Is Mine',
  'Religion',
  'Rituals',
  'Sailing',
  'Sailor',
  'Scent Tracking',
  'Sense of Smell',
  'Shrewd Negotiator',
  'Sleight of Hand',
  'Socialite',
  'Song Repertoire',
  'Stealth',
  'Stonesense',
  'Strategize',
  'Streetwise',
  'Survival',
  'Swimming',
  'Tactics',
  'Tear Things Apart',
  'Thief',
  'Throw',
  'Tracker',
  'Trade',
  'Tremor Sense',
  'Unveiled Threats',
  'Wilderness Lore',
  'Wisdom of Centuries',
] as const;

/**
 * Predefined conditions from the Daggerheart SRD.
 * Includes core conditions and common status effects from adversaries and domain cards.
 */
export const CONDITION_SUGGESTIONS = [
  // Core Conditions (from SRD)
  'Hidden',
  'Restrained',
  'Vulnerable',
  'Cloaked',
  // Common Status Effects (from adversaries, domain cards, equipment)
  'Bleeding',
  'Blinded',
  'Burning',
  'Charmed',
  'Cursed',
  'Dazed',
  'Deafened',
  'Dizzied',
  'Entranced',
  'Exhausted',
  'Frightened',
  'Frozen',
  'Glowing',
  'Horrified',
  'Incapacitated',
  'Invisible',
  'Paralyzed',
  'Petrified',
  'Poisoned',
  'Prone',
  'Silenced',
  'Slowed',
  'Stunned',
  'Weakened',
] as const;
