import type { LucideIcon } from 'lucide-react';
import {
  AlertTriangle,
  Axe,
  Backpack,
  BatteryMedium,
  Clapperboard,
  Coins,
  Compass,
  Dice5,
  FileText,
  Flame,
  FlaskConical,
  Globe,
  Handshake,
  Heart,
  Layers,
  Library,
  Map,
  MessageSquare,
  Moon,
  Puzzle,
  Repeat,
  Ruler,
  Settings,
  Shield,
  Skull,
  Sparkles,
  Star,
  Sword,
  Swords,
  Target,
  Tent,
  Theater,
  TrendingUp,
  User,
  Wind,
  Wrench,
} from 'lucide-react';

export const RulesSectionIcons: Record<string, LucideIcon> = {
  characterCreation: User,
  rolling: Dice5,
  combat: Swords,
  camping: Tent,
  navigation: Compass,
  adversaries: Skull,
  worldbuilding: Map,
  socialContract: Handshake,
  safetyTools: Shield,
  worldInfo: Globe,
  coreStats: TrendingUp,
  hitPoints: Heart,
  inventory: Backpack,
  diceRolling: Dice5,
  actionTokens: Repeat,
  experiences: Target,
  domainCards: Sparkles,
  hopeAndFear: BatteryMedium,
  hope: Star,
  stress: AlertTriangle,
  attack: Sword,
  scenes: Clapperboard,
  weapons: Axe,
  thresholds: Layers,
  conditions: Puzzle,
  distances: Ruler,
  death: Skull,
  shortRest: Tent,
  longRest: Moon,
  levelUp: TrendingUp,
  gold: Coins,
  crafting: FlaskConical,
  challenges: Compass,
  downtimeMoves: Sparkles,
  features: Wrench,
  hazards: AlertTriangle,
  environments: Wind,
  adversaryDesign: Puzzle,
  statBlocks: FileText,
  roleplay: Theater,
  sessionZero: Sparkles,
  encounterDesign: Flame,
  scaling: Ruler,
  campaignBuilding: Map,
  lore: Library,
  settings: Settings,
  modules: Puzzle,
  communication: MessageSquare,
} as const;
